Feature/database changed
ISAKids4Ever/RecruitmentApp pull request #27
Opened 2020-03-12 15:05 UTC by michalpzarzycki

Changed Realtime Database to Firestore Cloud - (there are a few details to be done)

2020-03-12 19:12 UTC, MateuszRostkowski requested changes

2020-03-12 19:12 UTC, MateuszRostkowski commented on src/components/Forum/Item.js
> -    firebase.database().ref('forum/' + question.qid).update({
this should live in forum service

2020-03-12 19:12 UTC, MateuszRostkowski commented on src/components/Forum/ItemDetail.js
> +    if(doc.exists) {
This should live in forum service

2020-03-12 19:12 UTC, MateuszRostkowski commented on src/components/Forum/ItemsList.js
> +        function handleSnapshot(snapshot) {
This should live in forum service

2020-03-14 14:49 UTC, ISAKids4Ever requested changes
Change usage of useState as suggested in comments, try to use HTML5 tags (it's not necessary to change before merge, but suggested)
Change double == comparison in App.js

2020-03-14 14:49 UTC, ISAKids4Ever commented on src/App.js
> +  if (isLoggedIn == null) {
Here should be triple === comparison, it keeps warning in a browser

2020-03-14 14:49 UTC, ISAKids4Ever commented on src/components/Forum/ItemDetail.js
>    const [commentText, setCommentText] = React.useState("");
Why are you importing useState as indepent from React and then use React.useState instead of just useState?

2020-03-14 14:49 UTC, ISAKids4Ever commented on src/components/Forum/ItemDetail.js
>            <div className={styles.questionSectionTitle}>{question.title}</div>
You could use here HTML5 tags like section for example

2020-03-15 17:58 UTC, MateuszRostkowski requested changes

2020-03-15 17:58 UTC, MateuszRostkowski commented on src/components/Forum/CreateItem.js
> +		console.log("newLink", newLink)
delete logs

2020-03-15 17:58 UTC, MateuszRostkowski commented on src/components/Forum/Item.js
>    function handleVote() {
this function should live in forum service

2020-03-15 17:58 UTC, MateuszRostkowski commented on src/components/Forum/Item.js
> +        <div style={{ margin: "0" }}>{question.votes.length}</div>
don't use inline styles

2020-03-15 17:58 UTC, MateuszRostkowski commented on src/components/Forum/ItemDetail.js
>            {question.created && <div style={{ width: '100%', color: "black" }}>Asked  {formatDistanceToNow(question.created, { addSuffix: true })}</div>}        <div className={styles.questionDescript
dont use inline styles

2020-03-15 17:58 UTC, MateuszRostkowski commented on src/components/Forum/ItemDetail.js
> +        {/* <div style={{ width: "30%", fontWeight: "bolder", fontSize: "150%" }} className={styles.likes}>LIKES: {question.votes.length}</div> */}
delete unused stuff

2020-03-15 17:58 UTC, MateuszRostkowski commented on src/firebase.js
> +// zakomentowane rzeczy to te, o ktorych pisalem, jak nie chcesz z nich skorzystac to poprostu je usun
dont use polish in comments

2020-03-15 17:58 UTC, MateuszRostkowski commented on src/screens/Forum/Forum.js
> +    // firebase.database().ref('forum').push({
This should live in forum service

2020-03-15 17:58 UTC, MateuszRostkowski commented on src/components/Forum/Item.js
>    function handleDelete() {
this forum should live in forum service

2020-03-15 17:58 UTC, MateuszRostkowski commented on src/components/Forum/Item.js
>          <div style={{ margin: '0', cursor: "pointer", display: "flex", justifyContent: "center", alignItems: "center", paddingTop: "35px", fontSize: "200%" }} onClick={handleVote}>
same here, don't use inline styles

2020-03-16 16:29 UTC, MateuszRostkowski requested changes

2020-03-16 16:29 UTC, MateuszRostkowski commented on src/components/Forum/ItemDetail.js
> +<<<<<<< HEAD
delete this

2020-03-16 16:29 UTC, MateuszRostkowski commented on src/components/Forum/ItemDetail.js
> +>>>>>>> 6b3f43c4d8c89024d74a2aaf568199c04e6b705b
resolve merging conflicts

2020-03-17 10:37 UTC, merged